services:
  client:
    build:
      context: ./clients/
      dockerfile: Dockerfile
    container_name: client
    ports:
      - 3000:3000
    networks:
      - app-network
    restart: unless-stopped

  node-app-screen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app-screen
    ports:
      - 5152:5152
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
