version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-ssl
    ports:
      - "443:443"
      - "8443:8443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - node-server
    networks:
      - app-network

  node-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    expose:
      - "5152"
    environment:
      - PORT=5152
    networks:
      - app-network
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command:
      - certbot
      - certonly
      - --webroot
      - -w
      - /var/www/certbot
      - --email
      - your@email.com
      - --agree-tos
      - --no-eff-email
      - -d
      - 145-223-97-55.nip.io
      - --non-interactive
      - --quiet

networks:
  app-network:
    driver: bridge
