version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-ssl
    ports:
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - node-server
    networks:
      - app-network

  node-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    expose:
      - "5152" # Internal only
    environment:
      - PORT=5152
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
