services:
  nginx:
    image: nginx:alpine
    ports:
      - "6767:6767" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - node-app-screen
    networks:
      - app-network
    restart: unless-stopped

  node-app-screen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app-screen
    expose:
      - "5152"
    environment:
      - PORT=5152
    networks:
      - app-network
    restart: unless-stopped
    
networks:
  app-network:
    driver: bridge
